### ISSUE TITLE
Add CLI

### ISSUE THREAD

**Issue by FokkeZB** [TheThingsNetwork/node-app-sdk#10]
Building on https://github.com/TheThingsNetwork/node-app-lib/blob/master/bin/monitor, but then properly using Commander.

Downlink example:

``` bash
./bin/ttn -r eu -a 'hello-world' -k 'my-key' -d 'my-uno' -m '{"led":true}` -p 1
```

Uplink example:

``` bash
./bin/ttn -r eu -a 'hello-world' -k 'my-key' -t `messages`
```

Topic could also be a full topic and can be used multiple times.

There should also be an `-o json` option to get the response outputted in json

**Comment by johanstokking** [comment]
What is the problem that we solve as compared to ttnctl?

This is another thing to maintain and seems confusing.

**Comment by FokkeZB** [comment]
Nothing really. I actually added https://github.com/TheThingsNetwork/node-app-lib/blob/master/bin/monitor at some point to quickly test but I agree it's better to stick with one CLI.
