### ISSUE TITLE
Add support to get confirmation of downlink message

### ISSUE THREAD

**Issue by FokkeZB** [TheThingsNetwork/node-app-sdk#11]
See https://www.npmjs.com/package/mqtt#mqttclientpublishtopic-message-options-callback

**Comment by FokkeZB** [comment]
@johanstokking is there a way we can get confirmation the downlink published is received by TTN?

**Comment by johanstokking** [comment]
We have two different stages of feedback in the making:
- Feedback events, see https://github.com/TheThingsNetwork/ttn/issues/159
- End-to-end confirmation, see https://github.com/TheThingsNetwork/ttn/issues/158

**Comment by FokkeZB** [comment]
Closed by #31
