### ISSUE TITLE
Accept any Buffer constructor argument as payload

### ISSUE THREAD

**Issue by FokkeZB** [TheThingsNetwork/node-app-sdk#12]
[Before we check](https://github.com/TheThingsNetwork/node-app-lib/blob/master/src/client.js#L28) if payload is an instance of `Buffer`, we should check if it's an array and in that case do `payload = new Buffer(payload)`.

**Comment by romeovs** [comment]
There are a lot of different things that are coercible to `Buffer` for instance:

```
const buf = new Buffer({ type: "buffer", data: [1, 2, 3] })
```

will also work.

I think we should just assume the input is a `Buffer` or coercible to `Buffer` and always wrap it in a `new Buffer` call. This will throw an error if it's not coercible to `Buffer` but makes sure we have all cases.

On a side node `new Buffer(new Buffer(x))` will result in the same buffer as `new Buffer(x)`, with the added advantage that we can't accidentally modify the original buffer.

**Comment by FokkeZB** [comment]
@romeovs mmm, actually... this has a challenge to it. When a users passes `{ type: "buffer", data: [1, 2, 3] }` how do I tell if he wants to send this as `payload_fields` or wrapped in buffer for `payload_raw`?

**Comment by romeovs** [comment]
We could have a special case for `{ "type": "Buffer" }` objects? But this needs to be documented, because it might introduce hard-to-track down bugs for end-user code. It would also be impossible to send a `payload_fields` with `{ "type": "Buffer" }` in it.

**Comment by johanstokking** [comment]
I think this is a very acceptable side effect when using the Node.js SDK.

**Comment by FokkeZB** [comment]
Mmm, I don't like it. Type is a pretty typical key and why would you pass `{ type: "buffer", data: [1, 2, 3] }` as payload if you could just pass `[1, 2, 3]`?

I actually don't see a lot [documented](https://nodejs.org/api/buffer.html#buffer_new_buffer_array) that would make sense to coerce.

I'd suggest:
- To wrap arrays, strings and Buffer objects (for the reason @romeovs gave) in `new Buffer()` for use with `payload_raw`
- To use (other) objects with `payload_fields`.
- Error on anything else.

**Comment by johanstokking** [comment]
Exactly. So `type: "Buffer"` is handled as Buffer, not as object passed to the encoder. Right?
