### ISSUE TITLE
Implement new app and device events

### ISSUE THREAD

**Issue by FokkeZB** [TheThingsNetwork/node-app-sdk#26]
As described at: https://github.com/TheThingsNetwork/ttn/tree/refactor/mqtt#device-events

**Comment by FokkeZB** [comment]
I suggest to get rid of the `activation` event and create a new API:

``` js
client.on('event', deviceId, eventName, function(deviceId, data) { });
```

It seems like `eventName` could be `up/errors` but also just `ack` or `activations` so I don't think we should split them up into another arg.

What do you think @johanstokking and @htdvisser?

**Comment by johanstokking** [comment]
It can be anything indeed, also a tree to make the event more specific. I would just pass the event type, which can be `down/ack` as parameter to the callback.

**Comment by FokkeZB** [comment]
So you suggest we:
- drop `eventName` as third argument for `on()`
- subscribe to all app or device events
- add `eventName` as second arguments for the callback?

That could give you lot of events

**Comment by FokkeZB** [comment]
Done: https://github.com/TheThingsNetwork/node-app-lib/pull/31
