### ISSUE TITLE
Downlink: Accept arguments for Buffer.from as alternative for Buffer

### ISSUE THREAD

**Issue by FokkeZB** [TheThingsNetwork/node-app-sdk#3]
This would allow the user to instead of :

``` js
client.downlink(devEUI, new Buffer('4869', 'hex'));
client.downlink(devEUI, Buffer.from('4869', 'hex')); // since 5.10
```

do:

``` js
client.downlink(devEUI, '4869', 'hex');
client.downlink(devEUI, 'Hi');
client.downlink(devEUI, [ 0x48, 0x69 ]);
```

**Comment by johanstokking** [comment]
Yep, good idea!

**Comment by FokkeZB** [comment]
As long as we also have the optional TTL and port I'm afraid this will only be confusing. Will add a label for consideration later.

**Comment by johanstokking** [comment]
We're dropping `ttl`, and `port` will have a more prominent place. I'd propose a signature like `downlink(devId, port, ...buffer)`

**Comment by FokkeZB** [comment]
@johanstokking, ok - but that does mean port is always required

**Comment by johanstokking** [comment]
The port is always required, but I think that in _most_ cases, users will use port 1. I don't know what's most convenient here, but it should be very convenient to specify the port.

**Comment by FokkeZB** [comment]
Would the port be something you'd lock in to for all downlinks or likely to diff per downlink? if it's not, then we could add a `setDownlinkPort()`.

**Comment by johanstokking** [comment]
Yeah it can differ; it really says something about the downlink.

**Comment by FokkeZB** [comment]
OK, then indeed it would be:

``` js
client.downlink(devEUI, port, '4869', 'hex');
client.downlink(devEUI, port, 'Hi');
client.downlink(devEUI, port, [ 0x48, 0x69 ]);
```

Although since port is a number and none of the buffer constructors start with number we could even support:

``` js
client.downlink(devEUI, '4869', 'hex');
client.downlink(devEUI, 'Hi');
client.downlink(devEUI, [ 0x48, 0x69 ]);
```

And would it make sense to also have:

``` js
client.downlink(message, '4869', 'hex');
client.downlink(message, 'Hi');
client.downlink(message, [ 0x48, 0x69 ]);
```

Which would use the devEUI and port form the message?

Of course too many signatures is confusing as well, but just trying to see how we can simplify it.

**Comment by FokkeZB** [comment]
I've given it another thought and I think it's better not to do this after all. To achieve consistency across SDKs for different platforms we should not mix a platform specific API for constructing buffers. Instead, the documentation for each platform SDK should explain how to create buffers on that platform. If we add support for protocol buffers later it will be a better alternative for this.
