### ISSUE TITLE
Make payload_raw always available as Buffer

### ISSUE THREAD

**Issue by johanstokking** [TheThingsNetwork/node-app-sdk#30]
See https://github.com/TheThingsNetwork/node-app-lib/commit/5f296387a93f4543122dd4f8079074c8fa7a6a87

**Comment by FokkeZB** [comment]
It already is. That's what https://github.com/TheThingsNetwork/node-app-lib/pull/15/files#diff-cf27c1d543e886c89cd9ac8b8aeaf05bR79 does
