### ISSUE TITLE
Update send to downlink in API.md

### ISSUE THREAD

**Issue by tjeerdytsma** [TheThingsNetwork/node-app-sdk#37]
The documentation in API.md still lists send. It seems it is replaced by the downlink method.

**Comment by FokkeZB** [comment]
It's actually the other way around. The current version on NPM uses `downlink()`, but the master (get it from NPM via: `npm i node-ttn@refactor`) uses `send()`.

**Comment by tjeerdytsma** [comment]
Thanks for your reply, now I understand. Took some time to dive a little deeper in npm. Just learned about tags (https://docs.npmjs.com/cli/dist-tag) :)

As the package name is 'ttn' and not 'node-ttn' I guess you mean `npm i ttn@refactor`. Correct?

**Comment by FokkeZB** [comment]
Correct, sorry for the confusion ;)
