### ISSUE TITLE
Inconsistent naming in message

### ISSUE THREAD

**Issue by johanstokking** [TheThingsNetwork/node-app-sdk#46]
`devId` vs `payload_raw`

**Comment by FokkeZB** [comment]
This is something from the staging version right? The master branch and refactor-tag version pass Device ID as separate argument and no longer inject it into the message:

https://github.com/TheThingsNetwork/node-app-lib/blob/master/src/client.js#L81-L82

Reopen if I'm mistaken

**Comment by johanstokking** [comment]
I mean, there is a `msg.devId` and a `msg.payload_raw` 

Or is this issue Node-RED specific?

**Comment by FokkeZB** [comment]
Yes. Previously also in this SDK but now only Node-Red since it needs all info in one object. Will create issue there.
