### ISSUE TITLE
message event

### ISSUE THREAD

**Issue by JuanRamino** [TheThingsNetwork/node-app-sdk#48]
Hi,

I see using the #message event in tests and documentation but when I try to use it I get no expected results.

Examples:
```
client.on('message', function(devId, data) {
    console.log(devId, data);
});
```
No output where ```client.on('uplink', function(msg) { console.log(msg) })```do the job

```
client.on('message', 'my-device', 'my-field', function(devId, data) {})
```
I get an error, *listener must be a function*

Thanks

**Comment by FokkeZB** [comment]
What version of the package are you using? The examples you give are for the refactor (2.x) version (`npm i --save ttn@refactor`) and I suspect that you are using the 1.x version?

We're getting ready to launch the new production environment this week at which point the new versions of the SDKs will become the main ones. That will be less confusing ;)

**Comment by JuanRamino** [comment]
Hi,

I'm using the 1.x version. I suspect it was a such problem.
I'm glad to know you are going to launch the new production enviroment.

Good work guys. Thanks for all
