### ISSUE TITLE
Device Add

### ISSUE THREAD

**Issue by hallard** [TheThingsNetwork/node-app-sdk#5]
Guys,
Sorry if my question is stupid, but do you think it's possible to have the dev Addr that TTN Dashboard shows returned in message also ? I'm sending data to Emoncms after receive and I would link to unique identify devices with Addr instead of EUID ?

![image](https://cloud.githubusercontent.com/assets/2471931/18221271/4a0ea532-717b-11e6-8110-d649442c01ba.png)

**Comment by FokkeZB** [comment]
@hallard stupid questions don't exist. The Dev Addr will be included in the next version of dashboard and the nodejs client: https://github.com/TheThingsNetwork/ttn/tree/refactor/mqtt#device-activations

**Comment by hallard** [comment]
Excellent, thanks ;)
