### ISSUE TITLE
SSL warning/error on Application Manager requests

### ISSUE THREAD

**Issue by noerw** [TheThingsNetwork/node-app-sdk#71]
Calling functions on an application results in the following SSL error emitted by node:
`E0911 18:11:13.687662896   11875 ssl_transport_security.c:227] Could not get common name of subject from certificate.`

However, the call is executed correctly.

```js
import * as ttn from 'ttn' // ttn@2.2.5
const app = await ttn.application('my-app', 'mytoken')
const devs = await app.devices() // -> SSL warning
```

**Comment by romeovs** [comment]
This is due to the way we build the self-signed handler certificates on the public community network.
The warning is harmless so you can ignore it.

In the meantime we will make sure to add the common name to new certificates. We'll put them live ASAP.

cc @htdvisser

**Comment by htdvisser** [comment]
@noerw I don't see this warning anymore, please reopen if it's still there when you try.
