### ISSUE TITLE
Cannot find module grpc_node.node

### ISSUE THREAD

**Issue by Dennishacq** [TheThingsNetwork/node-app-sdk#72]
I get the following error when i try to use require('ttn')

> Uncaught Exeption:
> Error: Cannot find module
> 'pathtomyproject\node_modules\ttn\node_modules\grpc\src\node\extention_bin...\grpc_node.node

I'm trying to build an application using Electron. My index.js:
```
const {app, BrowserWindow} = require('electron')
const path = require('path')
const url = require('url')

// Keep a global reference of the window object, if you don't, the window will
// be closed automatically when the JavaScript object is garbage collected.
let win

function createWindow () {
  // Create the browser window.
  win = new BrowserWindow({width: 800, height: 600})

  // and load the index.html of the app.
  win.loadURL(url.format({
    pathname: path.join(__dirname, 'index.html'),
    protocol: 'file:',
    slashes: true
  }))

  // Open the DevTools.
  //win.webContents.openDevTools()

  var ttn = require("ttn")
  var appID = "****************************************"
  var accessKey = "************************************************"

  ttn.data(appID, accessKey)
  .then(function (client) {
    client.on("uplink", function (devID, payload) {
      console.log("Received uplink from ", devID)
      console.log(payload)
    })
  })
  .catch(function (error) {
    console.error("Error", error)
    process.exit(1)
  })


  // Emitted when the window is closed.
  win.on('closed', () => {
    // Dereference the window object, usually you would store windows
    // in an array if your app supports multi windows, this is the time
    // when you should delete the corresponding element.
    win = null
  })
}

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', createWindow)

// Quit when all windows are closed.
app.on('window-all-closed', () => {
  // On macOS it is common for applications and their menu bar
  // to stay active until the user quits explicitly with Cmd + Q
  if (process.platform !== 'darwin') {
    app.quit()
  }
})

app.on('activate', () => {
  // On macOS it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (win === null) {
    createWindow()
  }
})

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and require them here.
```

**Comment by romeovs** [comment]
Does this only happen from within electron? Can you reproduce if you build a simple project on your machine (without electron)?

**Comment by Dennishacq** [comment]
This happens both with Electron and Node-Webkit. It does work when I use Socket.IO but I would like to create an application in HTML/NodeJs that doesn't require a webbrowser for the user interface

**Comment by romeovs** [comment]
Ok. To be clear, this sdk only works on Node.js, not the browser (which seems to be what you are after).

It's not been tested on custom runtimes like Electron, but it should work.

Can you try running the example scripts on your machine, I'm trying to make sure it is not a Windows issue first.

**Comment by Dennishacq** [comment]
The examples do work so i don't think it's a windows issue. 

My goal is to create a windows app that i can write in html/nodejs. 
Is there a program that makes this possible and has been tested?

**Comment by johanstokking** [comment]
Please have a look at [Electron](https://electron.atom.io). It's not tested with this module, but it's worth a try.

**Comment by Dennishacq** [comment]
After a new round of debugging i found a solution to the fix error.
I needed to run electron-rebuild (which wasn't working because there was an issue with my version of visual studio)
