### ISSUE TITLE
get EUIs for an application

### ISSUE THREAD

**Issue by noerw** [TheThingsNetwork/node-app-sdk#73]
When adding new devices an app EUI is required. This value currently cannot be retrieved with this SDK.
I would enhance either `application.get()` with an additional call to the account server, or add a new function `application.euis()`.

```js
request({
  url: `https://account.thethingsnetwork.org/applications/${appId}/euis`,
  headers: { 'Authorization': `Key ${key}` },
  json: true
}
```

I can send a PR if the feature is desired. I guess the account server domain should be configurable?

**Comment by johanstokking** [comment]
@noerw good suggestion!

I would add it indeed as separate call, to keep calls to the Handler separate from the Account Server.

And indeed, it should be configurable, but I'm quite sure it is already?

**Comment by romeovs** [comment]
>  I guess the account server domain should be configurable? 

[It most definitely is!](https://github.com/TheThingsNetwork/node-app-sdk/blob/master/DOCUMENTATION.md#accountclient)

**Comment by romeovs** [comment]
Closing because it is already implemented.
