### ISSUE TITLE
can I generate a proper devAddr with the API?

### ISSUE THREAD

**Issue by braadworst** [TheThingsNetwork/node-app-sdk#79]
I am working with the API to register a device, `application.registerDevice` just like in the examples. But I am stuck with the devAddr. According to the docs: https://www.thethingsnetwork.org/wiki/LoRaWAN/Address-Space there is a format to follow.

Now I need a devAddr for Indonesia and ABP. I am not sure how todo that, I would expect that I could generate that from the API.

How do I go about doing this? Furthermore, any following bytes after the ABP byte can they be anything, or is there are pattern as well?

Cheers,

Braadworst

**Comment by johanstokking** [comment]
Yes, your assumptions are correct. The Broker/NS issues a DevAddr, and we have an API for this available to support ABP.

Looping in @romeovs to see if this API is exposed or how to expose it. https://github.com/TheThingsNetwork/api/blob/master/protocol/lorawan/DevAddrManager.md

**Comment by romeovs** [comment]
The API is currently not exposed trough the `node-app-sdk` but it should be quite trivial to add it.

**Comment by johanstokking** [comment]
@braadworst @noerw any chance you can make a PR?

**Comment by braadworst** [comment]
Not right now. Need to do some preparing for field testing in january. It
is not my highest prio either. Just want to have the right address for ttn.
But it seems to work now too.

**Comment by romeovs** [comment]
Fixed by #82
