### ISSUE TITLE
Gateway methods

### ISSUE THREAD

**Issue by braadworst** [TheThingsNetwork/node-app-sdk#80]
How does one add a gateway via the node-app-sdk, cannot find any examples/docs for this.

**Comment by noerw** [comment]
The [account client](https://github.com/TheThingsNetwork/node-app-sdk/blob/master/src/account/account.js) currently only implements functions for application management.
Functions for gateway management could be added there quite easily, following the API defined [here](https://www.thethingsnetwork.org/docs/network/account/api.html).
