### ISSUE TITLE
DeprecationWarning on Buffer()

### ISSUE THREAD

**Issue by mariusvw** [TheThingsNetwork/node-app-sdk#85]
After upgrading to NodeJS 10.1 when receiving a message I get the following warning.

Currently it does not break anything yet.

```
[DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
```

**Comment by wachunei** [comment]
Probably related to this https://github.com/yarnpkg/yarn/issues/5477

**Comment by wachunei** [comment]
Yarn 1.7.0 solves this. https://github.com/yarnpkg/yarn/issues/5477#issuecomment-391504801
