### ISSUE TITLE
ttn with TypeScript

### ISSUE THREAD

**Issue by piechade** [TheThingsNetwork/node-app-sdk#87]
Could not find a declaration file for module 'ttn'. 'c:/Users/Dennis/Documents/Development/Projects/sensor-data/sensor-data-processing/server/node_modules/ttn/dist/index.js' implicitly has an 'any' type.
  Try `npm install @types/ttn` if it exists or add a new declaration (.d.ts) file containing `declare module 'ttn';`

**Comment by noerw** [comment]
For a past project I wrote a [TypeScript definition](https://github.com/52North/ttn-ogcswe-integration/blob/master/types/ttn.d.ts) (didn't check back in a while if it still works) in case you want this, but don't want to [generate a definition from the flow annotations](https://github.com/bcherny/flow-to-typescript)

**Comment by johanstokking** [comment]
We'll be adding TypeScript support in V3 SDK.
