### ISSUE TITLE
Security issue with hoek

### ISSUE THREAD

**Issue by chrisvoo** [TheThingsNetwork/node-app-sdk#94]
Hi,
I'm running the command `npm audit` to update all the libraries I can.
In my project, I use for example the `ttn` module, which has the following dependencies:

    ├─┬ ttn@2.3.1
    │ ├─┬ jsonwebtoken@7.4.3
    │ │ ├─┬ joi@6.10.1
    │ │ │ ├── hoek@2.16.3
    │ │ │ ├── isemail@1.2.0
    │ │ │ ├── moment@2.22.2 deduped
    │ │ │ └─┬ topo@1.1.0
    │ │ │   └── hoek@2.16.3 deduped
    │ │ ├─┬ jws@3.1.5
    │ │ │ ├─┬ jwa@1.1.6
    │ │ │ │ ├── buffer-equal-constant-time@1.0.1
    │ │ │ │ ├── ecdsa-sig-formatter@1.0.10
    │ │ │ │ └── safe-buffer@5.1.2 deduped
    │ │ │ └── safe-buffer@5.1.2 deduped
    │ │ ├── lodash.once@4.1.1
    │ │ ├── ms@2.0.0 deduped
    │ │ └── xtend@4.0.1 deduped

Audit found [two issues][1] with `hoek` package, patched for versions `> 4.2.0 < 5.0.0 || >= 5.0.3`. This package is used by sub-dependencies of `jsonwebtoken`.

  [1]: https://nodesecurity.io/advisories/566

**Comment by johanstokking** [comment]
Thanks @chrisvoo for reporting. Can you provide a PR?

**Comment by chrisvoo** [comment]
Sure, I'll try to spare some time for this.

**Comment by chrisvoo** [comment]
Sorry for the question, how should I create the PR? I see that I get a 403 if I push my branch there

**Comment by johanstokking** [comment]
Great, please see https://help.github.com/articles/creating-a-pull-request/

**Comment by chrisvoo** [comment]
Done, thank you!

**Comment by hsjakobsen** [comment]
Any update on this? It's not fixed as of version 2.3.1
I use NPM to update my ttn sdk

**Comment by johanstokking** [comment]
Looks like we never published this to npm. This repository is craving for CD...

Should be good now.
